### ISSUE TITLE
NoSuchMethod error when adding microsoft account

### ISSUE THREAD

**Issue by DoKM** [DJtheRedstoner/DevAuth#1]
Im trying to add a microsoft account currently.
after signing in it says return to game. Then it fails to launch.
Using a normal microsoft account with 2fa
Tried using the already logged in quick login and logging in fully again via a private tab.

Crash log
```
Caused by: java.lang.NoSuchMethodError: com.google.gson.JsonArray.add(Ljava/lang/String;)V
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.getXSTSToken(MicrosoftAuthProvider.java:308) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.oauthToMinecraft(MicrosoftAuthProvider.java:159) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.tryLogin(MicrosoftAuthProvider.java:143) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.login(MicrosoftAuthProvider.java:94) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.login(DevAuth.java:61) ~[DevAuth.class:?]
```

**Comment by ChachyDev** [comment]
What version of the game are you on?

**Comment by DoKM** [comment]
MC: 1.8.9
Forge: 11.15.1.2318
and asbyth's forgegradle

**Comment by DJtheRedstoner** [comment]
Somehow an older gson version is getting on the classpath, possibly from one of your dependencies. Try using the `dependencies` gradle task and searching for gson. The expected version is `2.4`.
