### ISSUE TITLE
Cannot authenticate under 18 Microsoft Accounts not in a family

### ISSUE THREAD

**Issue by patrickjonesuk** [DJtheRedstoner/DevAuth#3]
Using `DevAuth-forge-legacy-0.3.jar` with forge 1.8.9.

After authenticating with oauth in a private browser session, the program exits with the following stacktrace:
```
Caused by: java.lang.RuntimeException: Error logging in
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.tryLogin(MicrosoftAuthProvider.java:153) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.login(MicrosoftAuthProvider.java:94) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.login(DevAuth.java:61) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.processArguments(DevAuth.java:34) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.forge.legacy.ForgeLegacyBootstrap.processArguments(ForgeLegacyBootstrap.java:8) ~[ForgeLegacyBootstrap.class:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[Main.class:?]
	... 12 more
Caused by: java.lang.RuntimeException: Failed to get XSTS token
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.getXSTSToken(MicrosoftAuthProvider.java:318) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.oauthToMinecraft(MicrosoftAuthProvider.java:159) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.tryLogin(MicrosoftAuthProvider.java:143) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.login(MicrosoftAuthProvider.java:94) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.login(DevAuth.java:61) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.processArguments(DevAuth.java:34) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.forge.legacy.ForgeLegacyBootstrap.processArguments(ForgeLegacyBootstrap.java:8) ~[ForgeLegacyBootstrap.class:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[Main.class:?]
	... 12 more
Caused by: java.lang.RuntimeException: Received invalid response from the server: 401 Unauthorized body: {"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.httpError(MicrosoftAuthProvider.java:373) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.jsonPostRequest(MicrosoftAuthProvider.java:410) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.getXSTSToken(MicrosoftAuthProvider.java:314) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.oauthToMinecraft(MicrosoftAuthProvider.java:159) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.tryLogin(MicrosoftAuthProvider.java:143) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.auth.MicrosoftAuthProvider.login(MicrosoftAuthProvider.java:94) ~[MicrosoftAuthProvider.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.login(DevAuth.java:61) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.common.DevAuth.processArguments(DevAuth.java:34) ~[DevAuth.class:?]
	at me.djtheredstoner.devauth.forge.legacy.ForgeLegacyBootstrap.processArguments(ForgeLegacyBootstrap.java:8) ~[ForgeLegacyBootstrap.class:?]
	at net.minecraft.client.main.Main.main(Main.java) ~[Main.class:?]
	... 12 more
```

**Comment by ChachyDev** [comment]
I believe this is due to your Microsoft account is under 18. To resolve this issue you have to add your account to a family.
This occurs due to a limitation via Microsoft themselves

Reference documentation: https://inv.wtf/xboxonlinesafety.

Do note I'm not quite sure if this would work or not but may be a solution...

**Comment by patrickjonesuk** [comment]
> I believe this is due to your Microsoft account is under 18. To resolve this issue you have to add your account to a family.
> This occurs due to a limitation via Microsoft themselves
> 
> Reference documentation: https://inv.wtf/xboxonlinesafety.
> 
> Do note I'm not quite sure if this would work or not but may be a solution...

If this is a limitation by Microsoft, then why is it possible to authenticate with oauth from the official launcher, but not this way?

The documentation that you provided states that "Child accounts are all accounts for those under the age of 16 for the US & EU", however the DoB on the account is *not* less than 16.

**Comment by ChachyDev** [comment]
> > I believe this is due to your Microsoft account is under 18. To resolve this issue you have to add your account to a family.
> > This occurs due to a limitation via Microsoft themselves
> > Reference documentation: https://inv.wtf/xboxonlinesafety.
> > Do note I'm not quite sure if this would work or not but may be a solution...
> 
> If this is a limitation by Microsoft, then why is it possible to authenticate with oauth from the official launcher, but not this way?
> 
> The documentation that you provided states that "Child accounts are all accounts for those under the age of 16 for the US & EU", however the DoB on the account is _not_ less than 16.

It's possible via the Minecraft Launcher because Microsoft have their own special azure application

**Comment by patrickjonesuk** [comment]
> > > I believe this is due to your Microsoft account is under 18. To resolve this issue you have to add your account to a family.
> > > This occurs due to a limitation via Microsoft themselves
> > > Reference documentation: https://inv.wtf/xboxonlinesafety.
> > > Do note I'm not quite sure if this would work or not but may be a solution...
> > 
> > 
> > If this is a limitation by Microsoft, then why is it possible to authenticate with oauth from the official launcher, but not this way?
> > The documentation that you provided states that "Child accounts are all accounts for those under the age of 16 for the US & EU", however the DoB on the account is _not_ less than 16.
> 
> It's possible via the Minecraft Launcher because Microsoft have their own special azure application

That makes sense, but what about the fact that it's not a child account (according to the definition in the link that you referred to)?

**Comment by ChachyDev** [comment]
Well I'm not sure about that for Azure Applications it may be for > 18

**Comment by jsomeara** [comment]
Hi, can you try to add `&fl=dob,easi2` to the Authentication URL. I discovered this parameter in the Minecraft Launcher Authentication URL.

By Authentication URL, I mean the URL you use to login to Microsoft:
![image](https://user-images.githubusercontent.com/80555253/132137403-1cb49861-a53c-4990-924e-5275e52cc3f6.png)

I suspect `dob` might have something to do with it.

Haven't tested myself, but seems promising.

**Comment by patrickjonesuk** [comment]
> Hi, can you try to add `&fl=dob,easi2` to the Authentication URL. I discovered this parameter in the Minecraft Launcher Authentication URL.
> 
> By Authentication URL, I mean the URL you use to login to Microsoft:
> ![image](https://user-images.githubusercontent.com/80555253/132137403-1cb49861-a53c-4990-924e-5275e52cc3f6.png)
> 
> I suspect `dob` might have something to do with it.
> 
> Haven't tested myself, but seems promising.

I can test this and submit a PR if it solves the issue

**Comment by DJtheRedstoner** [comment]
I tried adding `fl=dob,easi2` query parameter to oauth url but I still get the `{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}` response. The account I used doesn't have a minecraft license attached, however that shouldn't make a difference.

**Comment by patrickjonesuk** [comment]
> I tried adding `fl=dob,easi2` query parameter to oauth url but I still get the `{"Identity":"0","XErr":2148916238,"Message":"","Redirect":"https://start.ui.xboxlive.com/AddChildToFamily"}` response. The account I used doesn't have a minecraft license attached, however that shouldn't make a difference.

Was just setting up an environment to test this when I saw your response, does this mean that there is no way to use an under-18 account with 3rd party oauth?

If that is the case, would it not be possible to authenticate the same way that the vanilla launcher does? Using the same oauth url and API endpoints, etc.

**Comment by DJtheRedstoner** [comment]
> Was just setting up an environment to test this when I saw your response, does this mean that there is no way to use an under-18 account with 3rd party oauth?

You can authenticate an under 18 account, it just needs to be part of a family.

> If that is the case, would it not be possible to authenticate the same way that the vanilla launcher does? Using the same oauth url and API endpoints, etc.

This really depends how the vanilla launcher implements it and I don't have the time or knowledge to reverse engineer/research how it does it. If someone else figured out how it worked, and it was possible to implement, I would consider implementing it.

**Comment by javaarchive** [comment]
Here's another reference, https://wiki.vg/Microsoft_Authentication_Scheme
It appears you need to somehow grab the minecraft launcher client id and substitute it in the url parameter.

Another rather tedious method is have the user start up a minecraft instance from the vanilla launcher and the mod can automatically grab a token from the launched java process's arguments.

**Comment by patrickjonesuk** [comment]
> Here's another reference, https://wiki.vg/Microsoft_Authentication_Scheme
> It appears you need to somehow grab the minecraft launcher client id and substitute it in the url parameter.
> 
> Another rather tedious method is have the user start up a minecraft instance from the vanilla launcher and the mod can automatically grab a token from the launched java process's arguments.

It wouldn't even be necessary to extract the endpoints from the launcher files, as it appears that the same requests are made by the browser when logging in to https://minecraft.net. I have been using this to (manually) obtain my session token, but I'm not sure it's possible to automate due to restricted redirect URIs.

**Comment by DJtheRedstoner** [comment]
I already have a method for logging in on under 18 accounts, I just need to finish the implementation.

> Here's another reference, https://wiki.vg/Microsoft_Authentication_Scheme
It appears you need to somehow grab the minecraft launcher client id and substitute it in the url parameter.

I already used wiki.vg a lot for this. The only thing special about the launcher client id is the minecraft themed background, its the authentication flow that matters for under 18 accounts.

**Comment by DJtheRedstoner** [comment]
I spent many hours working on an alternative authentication scheme, but I determined it was very complicated and too much effort for a small minority of users. I would be willing to implement it, but only if there is a significant enough demand.
